openapi: 3.0.2
info:
  title: API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /users:
    post:
      responses:
        200:
          description: It's OK

components:
  schemas:
  
    Parent:
      required:
        - status
      properties:
        status:
          type: string
      discriminator:
        propertyName: status
        mapping:
          CHILD_ONE: '#/components/schemas/ChildOne'
          CHILD_TWO: '#/components/schemas/ChildTwo'

    ChildOne:
      allOf:
        - $ref: '#/components/schemas/Parent'
        - type: object
        
    ChildTwo:
      allOf:
        - $ref: '#/components/schemas/Parent'
        - type: object
        